[package]
name = "cargo-craft"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive", "env"] }
tera = { version = "1.20.0", features = ["preserve_order"] }
toml = { version = "0.8.19", features = ["preserve_order", "display"] }
iocore = { path = "../gadgets/packages/iocore" }
serde = { version = "1.0.213", features = ["derive"] }
