cargo-features = ["edition2024"]

[package]
name = ""
version = "0.1.0"
edition = "2021"
autobins = false
autoexamples = false
autobenches = false

[package.metadata]
cargo-args = ["-Zmtime-on-use", "-Zavoid-dev-deps"]

[dependencies]
